@startuml modules_diagram

' Allow mixing classes and other UML elements (like files)
allowmixing

' Define the package structure
package "quebec_v2" {
    package "JSON_Validation" {
        class "validator" {
        ' Defined functions
        + load_portfolio()
        + load_schema ()
        + validate_portfolio()
        }
    }
    package "PriceApp" {
        class "price" {
        ' Defined functions
        + fetch_portfolio_sharpe_ratio()
        + load_and_validate_portfolio()
        + calculate_total_portfolio_value()
        + calculate_value_sharpe()
        }
    }
    package "UnitTests" {
        class "conftest"
        class "test_price" {
        ' Defined functions
        + price_data()
        + test_calculate_total_portfolio_value()
        + test_fetch_portfolio_sharpe_ratio()
        }
        class "test_schema_hypothesis" {
        ' Defined functions
         + validate_portfolio()
         + test_valid_portfolio()
         + test_valid_invalid_portfolio()
        }

    }
    package "scripts" {
        class "convert_safety_to_sarif" {
        ' Defined functions
        + find_files_for_package()
        + find_import_line()
        + generate_fingerprint()
        }
        class "trigger_safety"
    }
    package "Schemas" {
        ' Marking as a data class (JSON)'
        file "stock-schema.json" << (S, #FFAAAA) >>
    }
}

' Define external dependencies as classes
class "hypothesis" {
    ' Defined methods
    + given()
    + strategies()
}

class "hypothesis_jsonschema" {
    ' Defined methods
    + from_schema()
}


class "jsonschema" {
    ' Defined methods
    + exceptions()
}

class "pandas" {
    ' Defined methods
    + DataFrame()
    + read_json()
}
class "pytest" {
    ' Defined methods
}
class "yfinance" {
    ' Defined methods
    + download()
}

' Add standalone files
file "stock.json" << (S, #FFAAAA) >>
file "sample_portfolio.json" << (S, #FFAAAA) >>
file "requirements.txt" << (T, #FFFFFF) >>

@enduml