@startuml

actor User
group PriceApp
    User -> price.calculate_value_sharpe : Python3 -m PriceApp.price
    activate price.calculate_value_sharpe
    price.calculate_value_sharpe -> price.load_and_validate_portfolio
    activate price.load_and_validate_portfolio
    group JSON_Validation
        price.load_and_validate_portfolio -> validator.load_schema : schema location
        activate validator.load_schema
        price.load_and_validate_portfolio <-- validator.load_schema : loaded schema
        deactivate validator.load_schema
        price.load_and_validate_portfolio -> validator.load_portfolio : portfolio location
        activate validator.load_portfolio
        price.load_and_validate_portfolio <-- validator.load_portfolio : loaded portfolio
        deactivate validator.load_portfolio
        price.load_and_validate_portfolio -> validator.validate_portfolio : loaded portfolio and schema
        activate validator.validate_portfolio

        alt Valid Portfolio
            price.load_and_validate_portfolio <-- validator.validate_portfolio : valid portfolio decision
            price.calculate_value_sharpe <-- price.load_and_validate_portfolio : validated portfolio
            deactivate validator.validate_portfolio
            deactivate price.load_and_validate_portfolio
        else Invalid Portfolio
            price.load_and_validate_portfolio <-- validator.validate_portfolio : invalid portfolio decision
            price.load_and_validate_portfolio --> price.calculate_value_sharpe : invalid portfolio
            price.calculate_value_sharpe --> User : "Portfolio validation failed. Cannot calculate total value."
            deactivate validator.validate_portfolio
            deactivate price.load_and_validate_portfolio
        end
    end

    alt Valid Portfolio Path
        price.calculate_value_sharpe -> price.calculate_total_portfolio_value : validated portfolio, price data
        activate price.calculate_total_portfolio_value
        price.calculate_value_sharpe <-- price.calculate_total_portfolio_value : total portfolio value
        deactivate price.calculate_total_portfolio_value
    end

@enduml

