name: Security Scanning

on:
  push:
    branches: [ "main", "secure_coding_updates" ]
  pull_request:
    branches: [ "main", "secure_coding_updates" ]
  schedule:
    - cron: '26 22 * * 2'

jobs:
  security_scanning:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          exit_zero: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install Safety
      - name: Install Safety
        run: |
          python -m pip install --upgrade pip
          python -m pip install safety

      # Create output directory
      - name: Create output directory
        run: |
          mkdir -p ./scan-results
          chmod -R 755 ./scan-results  # Set permissions to be writable

      # Run Safety Scan
      #- uses: pyupio/safety-action@v1
      #  name: Safety Scan
      #  id: safety_scan
      #  with:
      #    #api-key: 2ecceb26-6325-44b8-9597-8c2b18493a6d
      #    api-key: ${{ secrets.SAFETY_API_KEY }}

      # Run Safety Scan and Save output to json file
      - name: Run Safety Scan
        run: |
          echo "Starting Safety scan..."
          safety scan --debug --json --stage production --output json > ./scan-results/safety_output.json 2>&1 || true
          echo "Safety scan complete."
          cat ./scan-results/safety_output.json
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
          SAFETY_STAGE: production


      # Check if issues exist in the Safety JSON
      - name: Check if vulnerabilities exist in the Safety JSON
        id: check_vulns
        run: |
          if jq '.scan_results.projects[].files[].results.dependencies[]? | select(.vulnerabilities.known_vulnerabilities | length > 0)' ./scan-results/safety_output.json; then
            echo "Vulnerabilities found."
            echo "Vulnerabilities_found=true" >> $GITHUB_ENV
          else
            echo "No vulnerabilities found."
            echo "Vulnerabilities_found=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      # Debug step: List scan-results directory to verify output
      - name: List scan-results directory
        run: |
          echo "Listing contents of ./scan-results:"
          ls -l ./scan-results || echo "No files found in ./scan-results"

      # Convert Safety results to SARIF if issues exist
      - name: Convert Safety results to SARIF
        if: ${{ env.Vulnerabilities_found == 'true' }}
        run: |
          echo "Converting safety_output.json to SARIF"
          python scripts/convert_safety_to_sarif.py ./scan-results/safety_output.json ./scan-results/safety_output.sarif || echo "SARIF conversion failed"
          echo "Conversion complete."

      # Debug step: Check if SARIF file was created.
      - name: Check if SARIF file was created
        run: |
          echo "Checking for SARIF file..."
          if [ -f ./scan-results/safety_output.sarif ]; then
            echo "SARIF file found."
            cat ./scan-results/safety_output.sarif
          else
            echo "SARIF file not found."
          fi

      # Check if the SARIF file exists before uploading it
      - name: Check if SARIF file exists
        id: check_sarif_file
        run: |
          if [ -f ./scan-results/safety_output.sarif ]; then
            echo "SARIF file exists, proceeding with upload."
            echo "sarif_file_exists=true" >> $GITHUB_ENV
          else
            echo "SARIF file does not exist."
            echo "sarif_file_exists=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      # Upload Safety results to Code Scanning Alerts if SARIF file exists
      - name: Upload Safety results to Code Scanning Alerts
        if: ${{ env.sarif_file_exists == 'true' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./scan-results/safety_output.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      # If no issues were found, print a message (optional)
      - name: No vulnerabilities found, skipping conversion
        if: ${{ env.Vulnerabilities_found == 'false' }}
        run: echo "No vulnerabilities were found, skipping SARIF conversion."